### PR TITLE
Last updates for the Wednesday tutorial

### PR DESCRIPTION
**Pull request by jpivarski**

### CODE REVIEW

**Comment by jhakala** [comment]
Hi Jim,

I took a look at your notebooks and they look great. I was thinking,
however (based on the fiascos that happened during my tutorial) that you
might want to have Marguerite or Kevin make a quick code review of whether
or not you're going to break Fermilab for one crazy reason or another. I'll
CC them to see if they have any input.

Best,
John

**Comment by kpedro88** [comment]
Everything in the histogrammar section looks safe to me. However, in [pyroot-histogram-acceleration.ipynb](https://github.com/FNALLPC/scientific-python-hats/blob/master/histogrammar/pyroot-histogram-acceleration.ipynb), rather than having each user xrdcp 220MB of files, it might be easier just to put them in some central location on nobackup, and point everyone there.

**Comment by jpivarski** [comment]
I made an alternative option to get them from my user area:

/uscms/home/pivarski/NOBACKUP/CMSSW_9_0_1/src/scientific-python-hats/histogrammar/sig_shuffled_*.root

so that we can pivot in the middle of the tutorial if EOS access is an
issue.

I understand why a FUSE-mounted frontend for EOS should exist and also not
be heavily used: it's convenient for some things but the nature of the
POSIX protocol forces it to be used in inefficient ways. It will always be
an uphill battle to convince physicists that they shouldn't use it, even
though it exists. (Maybe this fragile interface should only be accessible
to experts? Force everybody to say "eos ls" just like in Hadoop you have to
say "hadoop fs -ls" for everything.)

However, if 50 users download a total of 500 files (total of 11 GB) using
the *preferred* method (xrdcp), could that break anything? If so, how could
this system possibly scale? I know it does scale— but how could it if 500
requests in a 1 minute window is dangerous?

-- Jim

**Comment by kpedro88** [comment]
I don't think it will break anything to have everyone xrdcp the files - it's just kind of a waste of disk and network bandwidth.

(As much as I find the FUSE mount convenient when used appropriately, I have argued in the past that it should be disabled until it's fully stable... but this view doesn't seem to have much traction.)

**Comment by mverzett** [comment]
Just my 2 cents here:
I recently discovered that I was doing some things wrong (lt /eos/..../*/*/*.root), but I still find them extremely convenient. It would be nice if eosls supported posix regexes and if there was a eos-safe find equivalent.

**Comment by kpedro88** [comment]
The eos suite of commands is missing a lot of things (wildcard support, tab completion, etc.), but there is an `eos find` command - unfortunately you have to pipe the results into grep in order to do any regex-like selection.

**Comment by jhakala** [comment]
FWIW, David Lange is working on getting the python bindings for XRootD into
a future CMSSW [1]. It appears he's already merged in the necessary changes
to IB/CMSSW_9_1_X/gcc530
-- I wonder if it's possible to cmsrel that? In any case, that should
provide some useful tools for finding files.

John

[1] https://github.com/cms-sw/cmsdist/pull/2975

**Comment by mtonjes** [comment]
1) We cannot make EOS non-fuse mounted technically
2) The bunch of users copying things at the same time is not a problem, and it's a reasonable technique to teach them.
3) I did say something about the EOS regexp, we'll have an EOS expert visiting in May, and we're trying to setup having him available for an LPC computing discussion so we can bug him about this.

-Marguerite

**Comment by mtonjes** [comment]
I checked the code for Wednesday and Thursday and find nothing of concern. To rephrase what I said in another part of the thread, 500 users accessing some small amount of data in EOS at the same time is no more than a typical set of condor jobs, and of no concern.

What I didn't say was that Dave was actively monitoring during our last HATS, and we expect him (or someone) to be monitoring during our two HATS this week (and I am on slack with the sysadmins).

-Marguerite

http://uscms.org/uscms_at_work/computing/LPC/usingEOSAtLPC.shtml#doNot <http://uscms.org/uscms_at_work/computing/LPC/usingEOSAtLPC.shtml#doNot> --> some more "do not" above in this web page
http://uscms.org/uscms_at_work/computing/setup/batch_systems.shtml#condor_5 <http://uscms.org/uscms_at_work/computing/setup/batch_systems.shtml#condor_5> --> specific to condor so not relevant here, but I point it out for future HATS in case it comes into play

**Comment by jpivarski** [comment]
On Wed, Apr 26, 2017 at 10:06 AM, Marguerite <notifications@github.com>
wrote:

> To rephrase what I said in another part of the thread, 500 users accessing
> some small amount of data in EOS at the same time is no more than a typical
> set of condor jobs, and of no concern.


Okay, good. That's what I'd have thought— I was getting mixed messages
about what's dangerous and what's not.

Best,
-- Jim

**Comment by kpedro88** [comment]
https://github.com/FNALLPC/scientific-python-hats/pull/8#issuecomment-296729415
>Everything in the histogrammar section looks **safe** to me. However, in pyroot-histogram-acceleration.ipynb, rather than having each user xrdcp 220MB of files, it might be **easier** just to put them in some central location on nobackup, and point everyone there.

https://github.com/FNALLPC/scientific-python-hats/pull/8#issuecomment-297085456
>I don't think it will break anything to have everyone xrdcp the files - it's just kind of a **waste** of disk and network bandwidth.

(emphasis added)

**Pull request merged**
