### PR TITLE
Proposed Solution

### PR DESCRIPTION
**Pull request by aperloff**
I was asked to submit my pyROOT_essentials/backgroundHists.ipynb workbook as a proposed solution to the final question asked (make a stacked histogram of the QCD backgrounds).

### CODE REVIEW

**Comment by jhakala** [comment]
Thanks Alexx! I think it would be best to 'bury' this solution a little bit: how about you just commit this to a new branch of the repo. (You'll see I already include a "withOutput" branch, but I buried that to encourage the students to actually run the exercise themselves.)

**Comment by aperloff** [comment]
Should I just commit to the withOutput branch as well? That is, rather than making a whole new branch which will probably only have one or two commits.

**Comment by jhakala** [comment]
I think a new branch is better, since there were a bunch of last-minute commits made to master and not to withOutput (the diff might not be totally straightforward).

Thanks again!

**Comment by aperloff** [comment]
Okay, not a problem. I'll just call it "proposedSolutions" so that other people can commit their solutions to it as well.

**Comment by aperloff** [comment]
Closing this pull request. Will include the proposed solution in a new branch so it is slightly obfuscated.

**Pull request closed without merging**
